# curl -X 'DELETE' 
#  'https://localhost:5050/persons/0196016c-e151-4611-8434-c60623263e74' 
#  -H 'accept: application/json'
DELETE {{API_HostAddress}}/persons/0196016c-e151-4611-8434-c60623263e74
accept: application/json

###

# curl --request POST 
#  --url https://localhost:5050/persons 
#  --header 'Content-Type: application/json' 
#  --data '{
#  "dni": "89452371",
#  "firstName": "Laura",
#  "firstSurname": "Gómez",
#  "secondSurname": "Ramírez",
#  "gender": "Female",
#  "birthdate": "1995-08-21T00:00:00.000Z",
#  "maritalStatus": "Single",
#  "nationality": "Costa Rican",
#  "phoneNumber": "22457896",
#  "mobile": "88235679",
#  "email": "laura.gomez@example.com",
#  "isBaptized": true,
#  "skills": "Teaching, Leadership",
#  "address": {
#    "province": 1,
#    "canton": 2,
#    "district": 3,
#    "street": "Calle 45, Barrio Escalante",
#    "zipCode": "10104",
#    "longitude": -84.0912,
#    "latitude": 9.9281,
#    "plusCode": "WV84+476 San José"
#  },
#  "emergencyContact": {
#    "firstName": "José",
#    "lastName": "Mora",
#    "phoneNumber": "87945612"
#  },
#  "labor": {
#    "profession": "Engineer",
#    "laborSector": 2
#  },
#  "personalHealthStatus": {
#    "medicalCondition": false,
#    "description": ""
#  },
#  "membership": {
#    "membershipStatus": true,
#    "timeToCongregate": 3,
#    "area": "Youth Ministry",
#    "attendance": "Frequent"
#  }
#}
#'
POST {{API_HostAddress}}/persons
Content-Type: application/json

{
  "dni": "89452371",
  "firstName": "Laura",
  "firstSurname": "Gómez",
  "secondSurname": "Ramírez",
  "gender": "F",
  "birthdate": "1995-08-21T00:00:00.000Z",
  "maritalStatus": "Single",
  "nationality": "Costa Rican",
  "phoneNumber": "22457896",
  "mobile": "88235679",
  "email": "laura.gomez@example.com",
  "isBaptized": true,
  "skills": "Teaching, Leadership",
  "address": {
    "province": 1,
    "canton": 2,
    "district": 3,
    "street": "Calle 45, Barrio Escalante",
    "zipCode": "10104",
    "longitude": -84.0912,
    "latitude": 9.9281,
    "plusCode": "WV84+476 San José"
  },
  "emergencyContact": {
    "firstName": "José",
    "lastName": "Mora",
    "phoneNumber": "87945612"
  },
  "labor": {
    "profession": "Engineer",
    "laborSector": "Telecommunications"
  },
  "personalHealthStatus": {
    "medicalCondition": false,
    "description": ""
  },
  "membership": {
    "membershipStatus": true,
    "timeToCongregate": 3,
    "area": "Youth Ministry",
    "attendance": "Frequent"
  }
}

###

# curl -i http://httpbin.org/ip
GET {{API_HostAddress}}/health

###

# curl --request GET 
#  --url https://localhost:5050/persons
GET {{API_HostAddress}}/persons?pageNumber=1&pageSize=10


