apiVersion: 1

datasources:
  - name: MembershipPrometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # URL del contenedor de Prometheus
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 5s  # Intervalo de scraping
